apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: flexjar-analytics-api
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 384Mi
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: flexjar-analytics
        - application: bro-frontend
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        diskAutoresize: true
        databases:
          - name: flexjar
            envVarPrefix: DB
  env:
    - name: NAIS_CLUSTER_NAME
      value: dev-gcp
    - name: FLEXJAR_ANALYTICS_CLIENT_ID
      value: dev-gcp:team-esyfo:flexjar-analytics
