apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: flexjar-analytics-api
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: flexjar-analytics
        - application: flexjar-frontend
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-f1-micro
        databases:
          - name: flexjar
            envVarPrefix: DB
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
