apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: flexjar-analytics-api
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 4
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: false
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "5066bb56-7f19-4b49-ae48-f1ba66abf546" # isyfo - Intern Sykefraværsoppfølging
          - id: "ef4e9824-6f3a-4933-8f40-6edf5233d4d2" # esyfo - Ekstern Sykefraværsoppfølging
  accessPolicy:
    inbound:
      rules:
        - application: flexjar-analytics
        - application: bro-frontend
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: flexjar
            envVarPrefix: DB
  valkey:
    - instance: flexjar-cache
      access: readwrite
  envFrom:
    - secret: flexjar-analytics-api
  env:
    - name: NAIS_CLUSTER_NAME
      value: prod-gcp
    - name: FLEXJAR_ANALYTICS_CLIENT_ID
      value: prod-gcp:team-esyfo:flexjar-analytics
    - name: NAIS_API_GRAPHQL_URL
      value: https://console.nav.cloud.nais.io/graphql

